    <link rel="stylesheet" type="text/css" href="../dist/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../dist/plugins/codemirror/codemirror-pkg.min.css">
    <link rel="stylesheet" type="text/css" href="../dist/css/style.min.css">
    <link rel="stylesheet" type="text/css" href="../dist/css/components.min.css">